openapi: 3.0.0
info:
  title: Тестове заданиее от компании ООО "Априкод"
  description:
  version: 0.1.0

servers:
  - url: http://127.0.0.1:8081/v1
    description: Базовый путь для тестироания...

paths:
  /studios:
    get{format}:
      summary: Список студий-разработчиков игр
      parameters:
        - in: path
          name: format
          description: Формат ответа
          schema:
            type: string
            enum:
              - .xml
              - .json
      responses:
        default:
          description: Список сущностей студий-разработчиков
